# Example in https://dzone.com/articles/using-yaml-java-application

version: 1.1.2
released: 2020-02-10

# Logging Configuration
loggerConfig:
  fileName: mqttGateway.log
  maxFileSize: 1000000
  maxNumberOfFiles: 100
  appendFiles: true
  debugLevel: ALL

# MQTT Broker Config
broker:
  # For Dev
  host: local_mosquitto
  port: 1883
  # For Production
  #host: ea-pc165.ei.htwg-konstanz.de
  #port: 8883
  # From docker container
  # host: ttn_stack
  # port: 8883

database:
  # From docker container
  # host: influxdb
  host: 127.0.0.1
  port: 8086
  username: aut_labor
  password: secret
  name: aut_labor_db

# TTN Applications and the corresponding API Keys
applications:
  test-user-app: NNSXS.AY4E4ULPMZ6D6HJAFQ6EDAT5Q7L452YZTS4RZHA.3UVBF7VLN54UVI2YMF2EWCKQMRP7QFCGXYJXKETNDF6VH2R42TIA
  test-user-app2: NNSXS.XVTV3ZDWD6I77NML7O23UON73BRDLHYBSMRVOTQ.RWCM2CEN33GQKLPGELUJN7P7J5IUXJZEOITIH5PSHHJBETE77RRA

# MQTT Topics regex
regex: v3/(?<app>.*?)/devices/(?<device>.*?)/(?:(?<type>[\w&&[^/]]*)/?(?<downType>.*?)?)

# For List use
#List:
#  - element1
#  - element2
