# Example in https://dzone.com/articles/using-yaml-java-application

version: 1.0
released: 2020-01-06

# Logging Configuration
loggerConfig:
  fileName: mqttGateway.log
  maxFileSize: 10000
  maxNumberOfFiles: 10
  appendFiles: true
  debugLevel: ALL

# MQTT Broker Config
broker:
  # For Test
  host: localhost
  port: 1883
  # For Production
  #host: ea-pc165.ei.htwg-konstanz.de
  #port: 1883

# TTN Applications and the corresponding API Keys
applications:
  app1: some-api-key-214335009
  app2: some-api-key-769238943

# For List use
#List:
#  - element1
#  - element2
